#!/usr/bin/env bash
# encoding utf-8
# Created by: Acr4n1us
# Contact & Changelog: https://github.com/RamalhoSec
# Bitcoin: 3DppKRbA9Um3z4wnmVtkqnETnvwsip7WkC
# Version 0.1



#::required root 
[ "$UID" != "0" ] && { echo $red"Please runt this tool at root!"; exit 1 ;}


#::color
red='\033[31;1m'
green='\033[32;1m'
cyan='\033[36;1m'
yellow='Default \e[33m'
end='\033[m'
logoc=`printf $yellow""`

#::variables
name="Evillist"
version="0.1"
generator="crunch"
min=$1
max=$2
victiminfo=`echo ${3} | sed 's/,//g'`
vicinfodb=".victiminfo.db"
run=".run.sh"
file=".db.lst"
passwordlist="wordlist.lst"

#::remov other archives and add req:
rm $victiminfo $vicinfodb $run $file $passwordlist
test $(ls /usr/bin/${generator}) && echo "${name}{version}\n" || apt install ${generator}

#::logo
F_LOGO(){
  cat <<LOGO 
		${logoc}
          ^
         | |          This is a hold up! Put all your money in the
       @#####@        disk drive slot, and no one gets hurt!
     (###   ###)-.
   .(###     ###) \   +--------------------------------------------------------------+
  /  (###   ###)   )  	 [*]${name}: Create your direct wordlist with target info!
 (=-  .@#####@|_--"	 [*]Created by: Acr4n1us > I do not answer for your actions.
 /\    \_|l|_/ (\   	 [*]Contact: https://github.com/RamalhoSec/
(=-\     |l|    /     	 [*]Bitcoin: 3DppKRbA9Um3z4wnmVtkqnETnvwsip7WkC
 \  \.___|l|___/
 /\      |_|   /      	     How use this tool:
(=-\._________/			./${name} <min chars> <max chars> <info1,info2,info3,inf..>
 \             /        LOOK necessary use the (,)
   \._________/         one wordlist.txt will be created
     #  ----  #
     #   __   #
     \########/
LOGO
}



#::start de tool
if [ $# -lt 1 ]; then
   clear
   F_LOGO
   exit 1
fi
clear
F_LOGO
rm $run 1&> /dev/null 2&> /dev/null


#::crate the wordlist.txt
printf $red"\nHey wait a moment -> \n"
echo "crunch $1 $2 $victiminfo > ${file}" > $run && chmod +x $run
./$run 1&> /dev/null 2&> /dev/null

echo ${3} | sed 's/,/\n/g' > $vicinfodb
infos=`cat $vicinfodb | wc -l`

for i in $(seq 0 $infos); do infolist[${i}]=`cat $vicinfodb | head -$i | tail -1`; done
echo "====================>> If you want cancel just CTRL+C: "

for scan in "${infolist[@]}"; do 
	cat ${file} | grep $scan >> $passwordlist
done

#::end the tool and show created file
printf $green"====================>> Yeahhh excelent! your passlist is here: \n"$cyan && ls -lsha $passwordlist && printf $end"\n" 
