#!/usr/bin/env bash
# encoding utf-8
# Created by: Acr4n1us
# Contact & Changelog: https://github.com/RamalhoSec
# Bitcoin: 3DppKRbA9Um3z4wnmVtkqnETnvwsip7WkC
# Version 0.1



#::required root & check requeriments
[ "$UID" != "0" ] && { echo "Please runt this tool at root!"; exit 1 ;}
test /usr/bin/crunch && echo ""  || "[!]Please install crunch!"

#::color
red='\033[31;1m'
green='\033[32;1m'
cyan='\033[36;1m'
yellow='\033[33;1m'
end='\033[m'
logoc=`printf $yellow""`

#::variables
name="Evillist"
version="0.1"
dir_cfg="${HOME}/Evillist"
generator="crunch"
min=$1
max=$2
victiminfo=`echo ${3} | sed 's/,//g'`
run=".run.sh"
file="wordlist.lst"


#::logo
F_LOGO(){
  cat <<LOGO 
		${logoc}
          ^
         | |          This is a hold up! Put all your money in the
       @#####@        disk drive slot, and no one gets hurt!
     (###   ###)-.
   .(###     ###) \   +--------------------------------------------------------------+
  /  (###   ###)   )  	 [*]${name}: Create your direct wordlist with target info!
 (=-  .@#####@|_--"	 [*]Created by: Acr4n1us > I do not answer for your actions.
 /\    \_|l|_/ (\   	 [*]Contact: https://github.com/RamalhoSec/
(=-\     |l|    /     	 [*]Bitcoin: 3DppKRbA9Um3z4wnmVtkqnETnvwsip7WkC
 \  \.___|l|___/
 /\      |_|   /      	     How use this tool:
(=-\._________/			./${name} <min chars> <max chars> <info1,info2,info3,inf..>
 \             /        LOOK necessary use the (,)
   \._________/         one wordlist.txt will be created
     #  ----  #
     #   __   #
     \########/
LOGO
}



#::start de tool
if [ $# -lt 1 ]; then
   clear
   F_LOGO
   exit 1
fi
clear
F_LOGO
rm $run 1&> /dev/null 2&> /dev/null


#::crate the wordlist.txt
printf $red"\nHey wait a moment -> \n"
echo "crunch $1 $2 $victiminfo > $file" > $run && chmod +x $run
./$run 1&> /dev/null 2&> /dev/null
printf $green"Yeahhh excelent! your passlist is here: \n"$cyan && ls -lsha $file && printf "\n" && rm $run
